### PR TITLE
[FEATURE] - Add link to API from all navigation

### PR DESCRIPTION
**Pull request by tgandee79**
I added link to the API docs in the main navigation.  I looked through this entire site and I couldn't find any reference to the API for Ember-CLI.

Main Page Buttons
image

SideNav
image

Mobile:
image

### CODE REVIEW

**Comment by BrianSipple** [comment]
Huge 👍 . I was just going to suggest this as well. 

The API docs have been my go-to reference ever since I knew they existed, but for a while I didn't even know they existed. Based upon my experience in sharing this knowledge, that still appears to be the case for many a fellow embereño -- even among those more senior.

**Comment by BrianSipple** [comment]
One minor point, though: It might be better to use "API", as opposed to "DOCS", since everything is kind of the DOCS 😄 .

[Case in point](http://emberjs.com/):
screen shot 2016-08-19 at 02 23 00

**Comment by nathanhammond** [comment]
Agree with @BrianSipple ... let's use `API` and I'll be happy to merge.

**Comment by tgandee79** [comment]
Last Commits:

image

image

image

This last one wasn't in the `index.html` even as "Docs".  In there now.
image

**Pull request merged**
