### PR TITLE
readd fastclick

### PR DESCRIPTION
**Pull request by lazybensch**
addresses #64 

The app craches trying to attach the document to FastClick since the dependency was removed by the latest commits but will not be provided by non-apple devices. This breaks sidebar and overlay

### CODE REVIEW

**Comment by lazybensch** [comment]
it should either load fast-click in any case (since web browsers do not have this dep) or we should check and only attach it if the UA is apple.

in this pr i decided to just load fast-click in any case, if you want the second option i can change my pr

**Comment by leo** [comment]
Thank you for your effort! :blush:

However, I've removed the script on purpose. They reason why I did this is because the latest iOS (9.3) comes with "Fast Tap" built in. This basically removes the whole click delay and therefore the need for such a script.

I also understand that there are mobile operating systems which don't have that feature yet. However, it's a very huge script and not something that's important for making the site's content more accessible. Because of that, I've came to the conclusion that it's a better choice to simple remove it. Besides that, all the few remaining operating systems will probably adapt in a few months.

**Comment by kellyselden** [comment]
@lazybensch claims this fixes #64. @leo did you miss that or disprove that claim?

**Comment by leo** [comment]
I've chatted with @lazybensch on Slack. As far as I can see, those issues have already been fixed in 718e4b7eb97f41a5a4c2f89f81cb45a13f4a9617 and af6381869aa0df5a3651434e7d7f9d9411dc4f83.

**Comment by kellyselden** [comment]
@leo ok thanks! just making sure.

**Pull request closed without merging**
